# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-11-13 02:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_ninjas', '0002_auto_20181112_1751'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ninjas',
            old_name='dojo_id',
            new_name='dojo',
        ),
    ]
