# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-11-13 02:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_ninjas', '0005_auto_20181112_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='dojos',
            name='desc',
            field=models.TextField(default='Sample'),
            preserve_default=False,
        ),
    ]
